### ISSUE TITLE
create_db.py crashes with AttributeError

### ISSUE THREAD

**Issue by davidhewitt** [simonwardjones/python_cookbook#3]
Seems to get far enough to set up the db, but I don't know what damage this may be doing:

    Traceback (most recent call last):
      File "db_create.py", line 74, in <module>
        section=section.title())
    AttributeError: 'NoneType' object has no attribute 'title'

**Comment by simonwardjones** [comment]
Yeah - I forgot to add section to one of the recipes. I corrected the recipe. I don't really want a recipe not to have a section
